version: "3.3"

services:
  redis:
    image: redis
    volumes:
      - ./storage/redis:/data

  hubot:
    build: .
    image: skydropmx/hubot-slack
    volumes:
      - ./storage/scripts:/home/hubot/scripts
    env_file:
      - variables.env
    ports:
      - "127.0.0.1:2000:8080"

